version: '3'

services:
  node:
    build:
      context: ./node
      dockerfile: Dockerfile
    container_name: node
    entrypoint: dockerize -wait tcp://db:3306 -timeout 20s  docker-entrypoint.sh node index.js
    hostname: node
    tty: true
    volumes:
      - ./node:/src/usr/app
    ports:
      - "3000:3000"
    depends_on:
      - db

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    container_name: nginx
    hostname: nginx
    ports:
      - "8080:80"
    depends_on:
      - node

  db:
    image: mysql:5.7
    command: --innodb-use-native-aio=0
    container_name: db
    restart: always 
    tty: true
    volumes:
      - ./mysql:/docker-entrypoint-initdb.d
    environment:
      - MYSQL_DATABASE=nodedb
      - MYSQL_ROOT_PASSWORD=root